language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script: bash ./bin/build.sh

script:
- ls -al style.css

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/mismith0227/wp-theme-willow.git
  - secure: "CLSRRaxaMpCT95aXsYrEA2+LXFjDsQGz8efEVtpe8EEgII9T3lKzEG/rZQbfsrDDuHpxVSx9j3kQ6dyQNlVkPMuGXT7iKWnNDQloVb4AHwBt22N9EM9lRJJ4bua6hk8jHDwtOHQHbGPbJuY+a1EAsNj05E9v7d2tIUMsUCIUsWABpstEsuyziUSA08g+RHq0g4rdY+wJ20WKqhqa8vcKHkcbv0g6n0wUOsbWP6VsAAPc28stIgCfRp/cUYKCny2gvriuWnOY2M/aKkzVZn4QZo2db/PqmtYRUJCHFIoQv45nCLC+ey1OI2XntExs21Idimx/Kt8BqT2cbSrpnXFye7jrosT8s5hs36VWPYoRfJD+EQ2Sndtu/qw3gtEuEQqAaatf/AQPuz7U+6YCB/FgQ650TqEe4YgCh1tL2vIqUmfIEoYsrklDM+EqHukbw8/KvP9rwVhUYbTmX0wA4S5nfKcTwU64Lgw4MP9/LTb8ns92I4FoeE8VjqeGDQNUHvdZ3QnGi4hta6cYFGwmuQK/M2UU2j3aA75nn9O0OKEj5lxNIM9DCRa4gNl2t5H+KlHQ6Mq6jvZgUa5Mqs+TndPtPWNoGvPSqsPrhSUk1dy4kKEk7KU4xN4W8/pG34Vbs9l4t+w+OAOVNCngbZ7T/lnReH1t4jV4g9RlADPCE8COVGY="
